trigger:
  paths:
    include:
      - src/WebAPI/*
      - build-service.yml
  branches:
    include:
      - '*'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: SelfHostedLinuxUbuntu
    steps:
    - task: Docker@2
      displayName: Build DockerFile
      inputs:
        containerRegistry: 'laasaksgen'
        repository: 'commandlaunchermapperservice'
        command: 'build'
        buildContext : $(Build.Repository.LocalPath)
        Dockerfile: 'WebApi/Dockerfile'
        tags: '$(build.buildnumber)'
    - task: Docker@2
      inputs:
        containerRegistry: 'laasaksgen'
        repository: 'commandlaunchermapperservice'
        command: 'push'
        tags: '$(build.buildnumber)'
    - task: HelmInstaller@1
      displayName: 'Install Helm'
      inputs:
        helmVersionToInstall: v3.0.2
    - task: replacetokens@3
      inputs:
        rootDirectory: 'commandlaunchermapperservice'
        targetFiles: '**/values.yaml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: true
    - task: HelmDeploy@0
      displayName: 'helm package'
      inputs:
        azureSubscription: LaaS (d3e4d481-e08a-4d85-b01a-9ae56dab1e72)
        command: package
        chartPath: commandlaunchermapperservice
        chartVersion: '1.$(build.buildnumber)'
        save: false
        arguments: '--app-version 1.$(build.buildnumber)'
    - task: AzureCLI@1
      displayName: 'Azure CLI '
      inputs:
        azureSubscription: LaaS (d3e4d481-e08a-4d85-b01a-9ae56dab1e72)
        scriptLocation: inlineScript
        inlineScript: 'az acr helm push --name laasaksgen $(Build.ArtifactStagingDirectory)/commandlaunchermapperservice-1.$(Build.BuildNumber).tgz'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)'